### PR TITLE
BeidCards should manage the CardAndTerminalManager correctly

### PR DESCRIPTION
**Pull request by hanndecl**
Step 1: The class BeidCards creates the CardAndTerminalManager 
Step 2: Passes the CardAndTerminalManager to the cardManager. 
Step 3: When closing the BeidCards it should stop the cardManager and the CardAndTerminalManager. Otherwise the CardAndTerminalManager thread will remain. The CardManager don't stop the cardAndTerminalManager because he isn't the owner of the object.

### CODE REVIEW

**Comment by fcorneli** [comment]
Hi Hannes,

Thanks for reporting this issue. We'll have a look at it. Internal ticket: 5331
Is this a show stopper somehow?

Kind Regards,
Frank.

**Comment by hanndecl** [comment]
Frank,

For the moment this is a non-blocking issue, but we like to add this fix as soon as possible in our release.

Kind Regards
Hannes

**Comment by fcorneli** [comment]
Hi Hannes,

I'll schedule this for the next release.

Kind Regards,
Frank.

**Comment by hanndecl** [comment]
Frank,

Do you have any idea on the next release date?

Kind Regards,
Hannes

**Comment by fcorneli** [comment]
Merged fix.

**Pull request closed without merging**
